services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - fripcash_mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: fripcash

volumes:
  fripcash_mongo:
